const data = [
    {
        ticker: "NASDAQ.TXN",
        price: 78.31,
        f_score: 9,
        ben: 5,
        warren: 4,
        grade: 90,
        yield: 2.55,
        peg: 3.05,
        pe: 22.57,
        eps: 3.47,
    },
    {
        ticker: "NYSE:BBY",
        price: 56.29,
        f_score: 8,
        ben: 5,
        warren: 4,
        grade: 85,
        yield: 2.42,
        peg: 2.6,
        pe: 15.86,
        eps: 3.55,
    },
    {
        ticker: "NYSE:TNET",
        price: 32.45,
        f_score: 9,
        ben: 4,
        warren: 4,
        grade: 85,
        yield: 0,
        peg: 0.21,
        pe: 38.18,
        eps: 0.85,
    },
    {
        ticker: "NYES:MAS",
        price: 38.91,
        f_score: 8,
        ben: 5,
        warren: 4,
        grade: 85,
        yield: 1.03,
        peg: 0.61,
        pe: 26.11,
        eps: 1.49,
    },
    {
        ticker: "NYSE:FIX",
        price: 36.20,
        f_score: 8,
        ben: 5,
        warren: 4,
        grade: 85,
        yield: 0.83,
        peg: .85,
        pe: 21.29,
        eps: 1.7,
    },
    {
        ticker: "NYSE:BIG",
        price: 47.49,
        f_score: 7,
        ben: 5,
        warren: 4,
        grade: 80,
        yield: 2.11,
        peg: 4.29,
        pe: 14.3,
        eps: 3.32,
    },
    {
        ticker: "NYSE:LMT",
        price: 279.7,
        f_score: 7,
        ben: 5,
        warren: 4,
        grade: 80,
        yield: 2.6,
        peg: 31.63,
        pe: 22.23,
        eps: 12.58,
    },
    {
        ticker: "NYSE:MMS",
        price: 63.12,
        f_score: 8,
        ben: 5,
        warren: 3,
        grade: 80,
        yield: 0.29,
        peg: 3.9,
        pe: 23.91,
        eps: 2.64,
    },
    {
        ticker: "NASDAQ:INTU",
        price: 138.40,
        f_score: 7,
        ben: 5,
        warren: 4,
        grade: 80,
        yield: 0.98,
        peg: 9.38,
        pe: 45.53,
        eps: 3.04,
    },
    {
        ticker: "TSE:CLS",
        price: 18.14,
        f_score: 8,
        ben: 4,
        warren: 4,
        grade: 80,
        yield: 0,
        peg: 0.6,
        pe: 16.05,
        eps: 1.13,
    },
    {
        ticker: "NASDAQ:MIDD",
        price: 123.01,
        f_score: 8,
        ben: 4,
        warren: 4,
        grade: 80,
        yield: 0,
        peg: 5.27,
        pe: 24.12,
        eps: 5.1,
    },
    {
        ticker: "TSE:HWO",
        price: 4.25,
        f_score: 7,
        ben: 6,
        warren: 3,
        grade: 80,
        yield: 4.66,
        peg: 0.39,
        pe: 6.16,
        eps: 0.69,
    },
    {
        ticker: "NYSE:RHT",
        price: 98.19,
        f_score: 9,
        ben: 4,
        warren: 3,
        grade: 80,
        yield: 0,
        peg: 6.76,
        pe: 70.64,
        eps: 1.39,
    },
    {
        ticker: "NYSE:CL",
        price: 75.89,
        f_score: 7,
        ben: 4,
        warren: 4,
        grade: 75,
        yield: 2.11,
        peg: 34.95,
        pe: 26.82,
        eps: 2.83,
    },
    {
        ticker: "NYSE:SEE",
        price: 45.34,
        f_score: 7,
        ben: 4,
        warren: 4,
        grade: 75,
        yield: 1.41,
        peg: 0.67,
        pe: 16.67,
        eps: 2.72,
    },
    {
        ticker: "NASDAQ:MXIM",
        price: 45.78,
        f_score: 7,
        ben: 4,
        warren: 3,
        grade: 70,
        yield: 2.88,
        peg: 9.95,
        pe: 33.42,
        eps: 1.37,
    },
    {
        ticker: "NYSE:SSP",
        price: 18.01,
        f_score: 8,
        ben: 2,
        warren: 4,
        grade: 70,
        yield: 0,
        peg: 0.07,
        pe: 22.23,
        eps: 0.81,
    },
    {
        ticker: "NYSE:TIF",
        price: 92.31,
        f_score: 6,
        ben: 5,
        warren: 3,
        grade: 70,
        yield: 2.17,
        peg: 23.81,
        pe: 25.86,
        eps: 3.57,
    },
    {
        ticker: "NYSE:HRS",
        price: 110.91,
        f_score: 6,
        ben: 4,
        warren: 4,
        grade: 70,
        yield: 1.91,
        peg: 21.3,
        pe: 22.73,
        eps: 4.88,
    },
    {
        ticker: "NASDAQ:IDXX",
        price: 165.97,
        f_score: 7,
        ben: 3,
        warren: 3,
        grade: 65,
        yield: 0,
        peg: 13.68,
        pe: 68.02,
        eps: 2.44,
    },

]

module.exports = data